require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - db/schema.rb
    - spec/spec_helper.rb
    - db/migrate/*
    - bin/*
    - node_modules/**/*

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "config/routes.rb"

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodName:
  EnforcedStyle: snake_case

Rails/InverseOf:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
